version: 0.2

phases:
  build:
    commands:
      - echo "Building the PHP application"
      - php -v
      # Add any other build commands specific to your PHP app, such as generating assets or compiling templates
  post_build:
    commands:
      - echo "Copying files to deployment directory"
      - mv * /var/www/html/

artifacts:
  files:
    - '**/*'
    - '.env'

